addons:
  code_climate:
    repo_token: fc7f7e0563450afcb989fa87027bd2a68155359b6da11183c7f8690b185a766a

branches:
  except:
    - gh-pages

cache: bundler

env:
  - COVERAGE=true

language: ruby

notifications:
  email:
    - dev@bitaculous.com

rvm:
  - 2.5.3
  - 2.4.5

sudo: false